// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmejmxkmcougbjzidqnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZWpteGttY291Z2JqemlkcW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODkzNzEsImV4cCI6MjA2NzQ2NTM3MX0.PSWF7MfZQIzVokZ-mVD8eOw7lcgBjFUFQ1tfvAc408Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});